spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://127.0.0.1:3306/teacher?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1:3306/teacher?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
#      #Oracle需要打开注释
#      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


## 是否开启多数据源配置
configuration:
  switch:
    dynamic:
      datasource:
        enabled: false

dynamic:
  datasource:
    mainKey:
      #MySQL配置
      dbType: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3307/easycode?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
    sqliteKey:
      dbType: sqlite
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:data/martini.db?date_string_format=yyyy-MM-dd HH:mm:ss
      username:
      password:









